name: buildAPK
on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  Check-Flutter:
    name: check-flutter
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: '3.x'
          channel: 'stable'
      - run: flutter --version
  
  Build-APK:
    name: build-apk
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '12.x'
      - uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: '3.x'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk
      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'build/app/outputs/apk/release/app-release.apk'
          token: ${{ secrets.YOUR_GITHUB_TOKEN }}
  
