name: buildAPK
on:
  release:
    types: [created]
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  Check-Flutter:
    name: check-flutter
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: '3.x'
          channel: 'stable'
      - run: flutter --version
  
  Build-APK:
    name: build-apk
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '12.x'
      - uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: '3.x'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk
      - uses: skx/github-action-publish-binaries@release-2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'build/app/outputs/apk/release/app-release.apk'
  
