name: buildAPK
on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  Check-Flutter:
    name: check-futter
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.5'
          channel: 'stable'
      - run: flutter --version
  
